### PR TITLE
Added functionality to sort by yes vote

### PR DESCRIPTION
**Pull request by sshevlyagin**
I figured out how to add the sort. Not sure about the changes to parse.py. I needed to make those to get it running locally. What should I do about those changes?

### CODE REVIEW

**Comment by JoshData** [comment]
Yeah actually nothing needs to be done in parse.py because `computer_totals` is called there I think (check me?), so this should be fine.

But please don't commit your changes to `parse.py`. There's a reason it's set up the way it is.

And on your line that computes the percent, please use `self.total_plus` rather than `self.voters.filter(option__key='+').count()` since it will be a little faster if we can skip a database query. (It adds up when processing the 103,658 votes in the database.)

And I'm not sure there's a reason to use a DecimalField vs a FloatField. A float has enough precision to store all possible values of this field. I confirmed this will a little test expression to measure the difference between storing it as a float vs as a Decimal (with full precision stored):

    >>> max([ Decimal(i/435.0) - Decimal(i)/Decimal(435) for i in range(435+1)])
    Decimal('4.849249992610683739781379700E-17')

i.e. the difference is basically zero. So a float has plenty of precision.

The reason not to use a DecimalField is that I don't think you've set it up right. With `decimal_places=2, max_digits=4`, you've allocated for just two digits after the decimal point. And the way you're computing the percentage, these are numbers from 0 to 1. So you've only set it up to have precision to 1%. We wouldn't normally display more precision than that, but when sorting more precision will be needed.

So please use a FloatField, which is simpler anyway. ;)

**Comment by sshevlyagin** [comment]
I'm making those changes right now. To make the change work I added a 'percent_yes' to my local sqlite table. Does any other change need to happen to submit the schema change? On a related note, I saw that south (the tool to make schema changes easier) was commented out in your django setup. Why?

**Comment by sshevlyagin** [comment]
I made the change. I don't think I'm clear on the preferred way to do code migrations in this project. How is the new column percent_yes going to get picked up by the project? I did with python manage.py migrate locally.

**Comment by JoshData** [comment]
I do db migrations manually. Haven't gotten around to adding that now that Django has it built-in. So that's fine.

However, we do need to create some indexes, although I will probably have to figure out what indexes to create. So this may be done. I'll let you know more when I get a chance to test it. Thanks.

**Comment by JoshData** [comment]
Hey. Thanks for doing this!

I made some tweaks in e4121b4eedf4fcaa8c77f4dd6f2aacfb81e5e33a and then had to do some extra work to exclude votes that don't have yes/no votes when this sort order is chosen (in 2fb46f1f344470b12640e7beeedfdd73f6274e8f). Since I was in the code and recalculating these fields already, I also took care of wide/narrow margin sorting in 1704384950a06027b4290d9b806ffb87a9e094f6.

It will be live at https://www.govtrack.us/congress/votes in just a little bit (the page is cached).

Thanks again!

**Pull request merged**
