### PR TITLE
WIP: accessibility changes

### PR DESCRIPTION
**Pull request by joelcollinsdc**
Starting to work on the accessibility issues described in #129.  Some of these are likely to require discussion.

### CODE REVIEW

**Comment by JoshData** [comment]
(I haven't tried these changes locally but...) It looks like a good start, thanks!

**Comment by joelcollinsdc** [comment]
Pushed a commit (-f, hope that was OK) that tries to make the tabbed navigating look similar to mouse navigation.  Tested in safari and chrome, firefox keyboard navigating confuses me.

image

**Comment by JoshData** [comment]
Hey, is this ready to merge?

**Comment by joelcollinsdc** [comment]
I can get it in shape soon (today/tomorrow).  There are a few changes
needed like restyling headers after I reordered some H2s and 3's

**Comment by joelcollinsdc** [comment]
Would it be a problem for me to merge in master to this for testing all the new changes?  (This forked from cloud-deployment which doesn't appear to be merged into master yet...)

**Comment by joelcollinsdc** [comment]
I pushed some rudimentary changes to headings.  Some headings needed to be changed from h2 <--> h3 and also I added headings to tab body's when the content of the tab was important.  For the tabs... repeating the tab title in the tab pane does seem pretty duplicative but without a real header the document structure does seem pretty lacking.  Some examples below... feedback encouraged.

screen shot 2017-08-02 at 12 29 21 am


screen shot 2017-08-02 at 12 27 27 am

**Comment by joelcollinsdc** [comment]
I added some commits to support text alternatives for screen readers.  I tried to add a description to the sponsorship analysis and added the screen reader plugin for highcharts.  

screen shot 2017-08-02 at 1 35 16 am


I also added pending to the bill history table.  I suppose technically it wasn't necessary since a user that is unable to see colors would be able to infer from the lack of a date that an event hasn't happened yet...  

image

**Comment by JoshData** [comment]
Merged, thanks! I merged master into the branch, as well as some other major changes like upgrading Django from 1.7 to 1.11. I'm taking this opportunity to get as many ducks in a row as possible.

**Pull request merged**
