### PR TITLE
Register positions

### PR DESCRIPTION
**Pull request by wbt**
This contribution is intended to provide the functionality for Issue #124. There may be some additional refactoring (e.g. flatten migrations, consolidate CSS and JS with site-wide files, etc.) and changes desired, and some additional functionality can be added (e.g. associate anonymous positions with user on login) but the current code can be reviewed without that.  

License pending.

### CODE REVIEW

**Comment by JoshData** [comment]
For reference, I've moved the changes into a new branch (https://github.com/govtrack/govtrack.us-web/tree/userpositions2) and squashed your commits into https://github.com/govtrack/govtrack.us-web/commit/5b8466f571767c99298a32a86bca99325d20d2a1.

The branch also has updates to the panels to download the members' positions, plus disclaimer/privacy notices in appropriate places.

**Comment by wbt** [comment]
I can finally do licensing!  Under the condition that everything from Govtrack which is part of my contribution (e.g. code remaining from what I copied to use as a template) is licensed under Apache 2.0 (so that I *can* apply an open license on code I'd otherwise be unable to use or modify), I will be able to put my contribution under the same license.

**Comment by JoshData** [comment]
Great! I need to know two things....

First, what exact portions of GovTrack I need to apply the Apache license to. I've flattened this PR into the single commit at https://github.com/govtrack/govtrack.us-web/commit/f97f21c71c7ee7bfa0aafa11c63cb0943db6b8a0, which is what I will merge. Most of the commit is original work. The parts that appear to be plausibly derivative of GovTrack are the parts that follow the way the emoji reactions work and the master page layout/template. Do you agree?

Second, because these are sub-parts of GovTrack that aren't all located in a single place, I need to know what CMU will accept as me applying the license in lieu of the usual way of doing this (a note in the README and a LICENSE file). I'd be glad to write you a signed letter saying that I am making those parts open source. Or I could add a copyright/license notice at certain points in the source code near the portions that we think you are creating a derivative work of. What will work?

**Comment by wbt** [comment]
Your assessment in the first paragraph seems reasonably accurate.  To be precise, it would be any lines in any part of this PR, whether identified now or later as being from GovTrack or from me.  I don't think it's worth spending effort distinguishing between which lines are from GovTrack to begin with and which ones aren't as they'll be under the same license at the end of this thread.  If someone really cares about the distinction later, the history is preserved to enable such analysis. 

Though I'm not a lawyer, I think a comment here in the PR discussion should be sufficient, and embedding of licensing information in the code or an out-of-band letter are probably not strictly necessary (though you can if you want to :-).  You could add a license text file saying something like "Limited portions of this code are licensed under the Apache License 2.0 (https://www.apache.org/licenses/LICENSE-2.0); see https://github.com/govtrack/govtrack.us-web/pull/148."

**Comment by JoshData** [comment]
Ok, so I'll just say it here:

I (hereby) license the emoji reactions, the master page template, and any other parts of the GovTrack source code in this repository (https://github.com/govtrack/govtrack.us-web) from which Ben's work in this pull request is based under the terms of the Apache License 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

If that's all you need, you can follow up with the same for your code. If that's not all you need, let me know.

**Comment by wbt** [comment]
I hereby release my contributions in this pull request, as made and as merged and anything in between, under the terms of the Apache License 2.0 (https://www.apache.org/licenses/LICENSE-2.0).

**Comment by JoshData** [comment]
Excellent. Merging and deploying now. I'll follow-up in email.

**Pull request closed without merging**
